name: update readme

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pygithub

      - name: update readme
        env:
          GIHTUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python updater.py
