name: update readme

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pygithub

      - name: update readme
        env:
          GIHTUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          python updater.py

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: Update resources
          github-token: ${{ secrets.TOKEN }}
